### ISSUE TITLE
More values

### ISSUE THREAD

**Issue by AndreasSMoe** [kvasbo/tibber-pulse-connector#1]
Hi,
Sorry, no idea how to create a new tibber-pulse-connector (npm), but could you please also add values for measurement in the next tibber-pulse-connector editon:
voltagePhase1
voltagePhase2
voltagePhase3
currentPhase1
currentPhase2
currentPhase3
lastMeterConsumption

excellent work on the npm tibber-puls-connector

regards
Andreas

**Comment by kvasbo** [comment]
Sure :)

**Comment by kvasbo** [comment]
Just released a new version with this functionality.
